import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'zh-CN' | 'en-US'
export type ThemeMode = 'light' | 'dark'

const LOCALE_STORAGE_KEY = 'wyckoff.locale'
const THEME_STORAGE_KEY = 'wyckoff.theme'

const ZH = {
  'app.subtitle': '智能投研助手',
  'nav.chat': '读盘室',
  'nav.analysis': '单股分析',
  'nav.battle': '多股对抗',
  'nav.portfolio': '持仓诊断',
  'nav.tracking': '跟踪',
  'nav.tailBuy': '尾盘记录',
  'nav.export': '数据导出',
  'nav.guide': '功能说明',
  'nav.capabilities': '能力边界',
  'nav.settings': '设置',
  'external.home': '项目主页',
  'external.github': 'GitHub',
  'action.logout': '退出',
  'action.refresh': '刷新',
  'action.save': '保存',
  'action.cancel': '取消',
  'action.delete': '删除',
  'prefs.theme': '主题',
  'prefs.language': '语言',
  'prefs.light': '浅色',
  'prefs.dark': '深色',
  'prefs.switchToEnglish': 'Switch to English',
  'prefs.switchToChinese': '切换到中文',
  'common.loading': '加载中...',
  'common.empty': '暂无数据',
  'common.code': '代码',
  'common.name': '名称',
  'common.date': '日期',
  'common.stockCode': '股票/ETF代码',
  'common.exampleCode': 'A股/ETF: 601318 · 美股: AAPL · 港股: 00700',
  'common.configureFirst': '请先在设置页配置',
  'common.invalidStockCode': '请输入有效代码（A股/ETF 6位数字，美股英文代码，港股5位数字）',
  'common.marketHint': '支持 A 股、ETF、美股、港股 · 美股港股需',
  'common.tickflowLink': '购买 TickFlow 数据源',
  'common.rows': '条',
  'common.stocks': '支',
  'login.email': '邮箱',
  'login.password': '密码',
  'login.submit': '登录',
  'login.register': '注册',
  'login.processing': '处理中...',
  'login.hasAccount': '已有账号？',
  'login.noAccount': '没有账号？',
  'login.operationFailed': '操作失败',
  'login.rememberAccount': '记住账号',
  'login.passwordManagerHint': '密码由浏览器或系统密码管理器安全保存',
  'settings.title': '设置',
  'settings.account': '账号信息',
  'settings.saved': '已保存',
  'settings.saveFailed': '保存失败: {message}',
  'settings.saving': '保存中...',
  'settings.saveConfig': '保存配置',
  'settings.dataSources': '数据源',
  'settings.tickflowPromo': 'TickFlow 行情数据源（支持项目）',
  'settings.purchaseLink': '购买链接',
  'settings.modelConfig': '模型配置',
  'settings.oneRoutePromo': '1Route 模型中转（支持项目）',
  'settings.provider': '读盘室供应商',
  'settings.oneRouteNoAccount': '还没有 1Route 账号？',
  'settings.oneRouteInvite': '通过购买链接开通',
  'settings.apiKey': 'API Key',
  'settings.model': '模型',
  'settings.baseUrl': 'Base URL',
  'settings.notifications': '通知推送',
  'settings.feishuWebhook': '飞书 Webhook',
  'settings.wecomWebhook': '企业微信 Webhook',
  'settings.dingtalkWebhook': '钉钉 Webhook',
  'analysis.title': '单股分析',
  'analysis.missingTitle': '开始分析前还差一步配置',
  'analysis.missingModel': '请先配置读盘室模型的 API Key 和模型名称',
  'analysis.missingDataSource': '请先配置 TickFlow 股票数据源 API Key',
  'analysis.goSettings': '前往设置页',
  'analysis.modelRequirement': '读盘室模型 API Key / 模型',
  'analysis.dataRequirement': 'TickFlow 股票数据源 API Key',
  'analysis.missingPrefix': '请先在设置页完成配置：{items}',
  'analysis.configError': '配置状态异常，请前往设置页检查后重试',
  'analysis.exampleCode': 'A股/ETF: 601318 · 美股: AAPL.US · 港股: 00700.HK',
  'analysis.searchPlaceholder': '输入股票名称或代码，例如 中国平安 / AAPL / 腾讯',
  'analysis.searching': '搜索中...',
  'analysis.noSearchResults': '未找到匹配标的',
  'analysis.invalidStockCode': '请输入有效代码：A股/ETF 6位数字；美股/港股用 TickFlow 标准代码，例如 AAPL.US / 00700.HK',
  'analysis.marketHint': 'A 股/ETF 可填 6 位代码；美股/港股请填 TickFlow 标准代码（AAPL.US / 00700.HK），并需',
  'analysis.noKlineData': '没有获取到有效日线数据，请检查股票代码、TickFlow Key 或稍后重试。',
  'analysis.failed': '分析失败',
  'analysis.analyzing': '分析中...',
  'analysis.progressResolve': '解析代码...',
  'analysis.progressKline': '拉取 K 线...',
  'analysis.progressLLM': '模型分析中...',
  'analysis.start': '开始分析',
  'analysis.reportTitle': '威科夫大师研报',
  'analysis.chartTitle': '近 320 交易日结构图',
  'analysis.chartSubtitle': 'K 线、均线、支撑/压力与威科夫结构标记均来自 TickFlow 日线数据',
  'analysis.emptyTitle': '输入股票代码，开始威科夫大师分析',
  'analysis.emptySubtitle': '配置 TickFlow Key 后可显示 K 线图',
  'chat.title': '读盘室',
  'chat.noApiKey': '未配置 API Key',
  'chat.newChat': '新对话',
  'chat.emptyTitle': '我是威科夫，只看供需和主力行为',
  'chat.tryAsk': '试试问我：',
  'chat.fullVersionPrefix': '网页版暂不支持会话历史、Agent 记忆与后台任务',
  'chat.unlockFull': '解锁完整能力',
  'chat.generating': '生成回复中...',
  'chat.thinking': '思考中...',
  'chat.placeholder': '输入消息...',
  'chat.configureLLM': '请先在设置页配置 LLM API Key',
  'chat.requestFailed': '请求失败',
  'chat.toolCalls': '{count} 个工具调用',
  'chat.reasoningSteps': '{count} 个推理步骤',
  'chat.prompt.portfolio': '我有什么持仓',
  'chat.prompt.market': '大盘怎么样',
  'chat.prompt.recent': '最近复盘记录',
  'chat.prompt.search': '帮我搜一下宁德时代',
  'chat.prompt.screen': '帮我选股',
  'chat.prompt.strategy': '给个操作建议',
  'tool.search_stock': '搜索股票',
  'tool.view_portfolio': '查看持仓',
  'tool.market_overview': '大盘水温',
  'tool.market_history': '大盘回看',
  'tool.query_recommendations': '威科夫形态复盘',
  'tool.query_tail_buy': '尾盘记录',
  'tool.plan_portfolio_update': '调仓方案',
  'tool.execute_portfolio_update': '执行调仓',
  'tool.analyze_stock': '个股诊断',
  'tool.screen_stocks': '漏斗选股',
  'tool.generate_ai_report': 'AI 研报',
  'tool.generate_strategy_decision': '策略建议',
  'portfolio.title': '持仓诊断',
  'portfolio.whitelistSubtitle': '已为白名单用户读取数据库持仓，选择任意持仓即可基于实时行情做诊断。',
  'portfolio.manualSubtitle': '录入当前持仓后触发行情数据源和模型诊断；若数据源额度或并发受限，会提示升级入口。',
  'portfolio.dbMode': '数据库持仓',
  'portfolio.manualMode': '手动录入',
  'portfolio.missingModel': '请先在设置页配置读盘室模型 API Key 和模型名称',
  'portfolio.failed': '持仓诊断失败',
  'portfolio.invalidCode': '请输入有效代码：A股/ETF 6位数字；美股/港股用 TickFlow 标准代码，例如 AAPL.US / 00700.HK',
  'portfolio.totalAssets': '总资产（成本）',
  'portfolio.freeCash': '可用资金',
  'portfolio.positionCount': '持仓数',
  'portfolio.positionCost': '持仓成本',
  'portfolio.empty': '暂无持仓，可通过 CLI 或读盘室 Agent 添加',
  'portfolio.emptyDb': '数据库里暂无持仓。可以先通过读盘室或 CLI 添加持仓后再回来诊断。',
  'portfolio.code': '股票代码',
  'portfolio.name': '股票名字',
  'portfolio.shares': '数量',
  'portfolio.costPrice': '成本价',
  'portfolio.buyDate': '建仓日',
  'portfolio.action': '操作',
  'portfolio.analyzeThis': '诊断',
  'portfolio.startDiagnosis': '开始诊断',
  'portfolio.dataHint': '诊断会读取近 320 根日线 K 线；数据源权限不足、并发或额度受限时会提示升级 TickFlow。',
  'portfolio.snapshot': '持仓快照',
  'portfolio.fullDiagnosis': '整体诊断',
  'portfolio.fullDiagnosisHint': '综合分析所有持仓+现金的资产配置',
  'portfolio.fullLoading': '正在分析全部持仓...',
  'portfolio.addPosition': '添加持仓',
  'battle.title': '多股对抗',
  'battle.subtitle': '输入任意数量股票，系统并发读取 TickFlow 日线，比较相对强弱并给出威科夫视角的胜负结论。',
  'battle.inputLabel': '股票代码或名称',
  'battle.inputHint': '支持换行、空格、逗号分隔；例如 中国平安、AAPL、00700.HK。输入数量不设上限。',
  'battle.start': '开始对抗',
  'battle.running': '对抗中...',
  'battle.missingModel': '请先在设置页配置读盘室模型 API Key 和模型名称',
  'battle.overlay': '重叠对比',
  'battle.separate': '分开展示',
  'battle.overlayLimit': '重叠数量',
  'battle.selectAll': '全选',
  'battle.clearAll': '反选清空',
  'battle.score': '强弱分',
  'battle.drawdown': '回撤',
  'battle.report': '强弱结论',
  'tracking.title': '威科夫形态复盘',
  'tracking.description': '此页仅展示复盘表中最新 30 个复盘交易日的数据；这 30 个日期按数据库实际存在的入选日计算，不按连续自然日补齐。',
  'tracking.range': '当前保留范围：{oldest} 至 {latest}。',
  'tracking.window': '复盘交易日窗口',
  'tracking.windowOption': '近{size}个复盘交易日',
  'tracking.currentWindow': '当前窗口：{oldest} 至 {latest}，{count} 个复盘交易日，{rows} 条复盘记录',
  'tracking.coveredStocks': '覆盖股票数',
  'tracking.avgChange': '近{size}个复盘交易日平均涨幅',
  'tracking.bestChange': '最高涨幅',
  'tracking.worstChange': '最大跌幅',
  'tracking.totalRecommendations': '总入选次数',
  'tracking.winRate': '胜率',
  'tracking.avgWin': '平均盈利',
  'tracking.avgLoss': '平均亏损',
  'tracking.profitFactor': '盈亏比',
  'tracking.times': '次',
  'tracking.searchPlaceholder': '搜索代码或名称...',
  'tracking.onlyAI': '只看 AI 入选',
  'tracking.sortDate': '按日期',
  'tracking.sortChange': '按涨幅',
  'tracking.sortMfe': '按 MFE',
  'tracking.sortMae': '按 MAE',
  'tracking.sortScore': '按信号分',
  'tracking.sortRecommendCount': '按推荐次数',
  'tracking.sortDesc': '降序',
  'tracking.sortAsc': '升序',
  'tracking.recommendDate': '入选日',
  'tracking.recommendCount': '推荐次数',
  'tracking.initialPrice': '初始价',
  'tracking.currentPrice': '现价',
  'tracking.changePct': '涨跌幅',
  'tracking.score': '信号分',
  'tracking.scoreRaw': '形态',
  'tracking.scorePriority': '优先级',
  'tracking.mfePct': 'MFE',
  'tracking.maePct': 'MAE',
  'tracking.rangeAmpPct': '区间振幅',
  'tracking.empty': '暂无复盘记录',
  'tracking.tabCN': 'A股',
  'tracking.tabUS': '美股',
  'tracking.tabHK': '港股',
  'tracking.betaLocked': '功能内测中，如需体验请联系开发者',
  'tailBuy.title': '尾盘记录',
  'tailBuy.total': '共 {count} 条',
  'tailBuy.empty': '暂无尾盘买入记录',
  'tailBuy.emptySubtitle': '等待下一次尾盘策略执行后刷新',
  'tailBuy.signal': '信号',
  'tailBuy.ruleScore': '规则分',
  'tailBuy.priorityScore': '优先级分',
  'tailBuy.llmDecision': 'LLM决策',
  'tailBuy.reason': '理由',
  'export.title': '数据导出',
  'export.days': '回溯天数',
  'export.adjust': '复权',
  'export.qfq': '前复权',
  'export.hfq': '后复权',
  'export.noneAdjust': '不复权',
  'export.fetching': '获取中...',
  'export.fetch': '获取数据',
  'export.configureTickflow': '请先在设置页配置 TickFlow API Key',
  'export.apiError': 'TickFlow API 错误 ({status}): {message}',
  'export.noData': '未获取到有效数据，请检查股票代码或稍后重试',
  'export.failed': '导出失败',
  'export.streamlitLink': '可移步 Streamlit 版本使用完整导出功能 ->',
  'export.downloadCsv': '下载 CSV ({fileName})',
  'export.previewCount': '共 {count} 条（预览前 10 条）',
  'export.previewCountMore': '共 10+ 条（预览前 10 条）',
  'export.emptyTitle': '输入股票代码，导出历史行情 CSV',
  'export.emptySubtitle': '基于 TickFlow API，支持前复权/后复权',
  'export.needBatch': '需要批量导出或自定义数据源？前往 Streamlit 版本 ->',
  'guide.title': '功能说明',
  'guide.subtitle': 'Wyckoff 智能投研助手围绕读盘、选股、跟踪、持仓和复盘组织工作流。',
  'guide.core': '核心功能',
  'guide.coreDesc': '从自然语言读盘到结构化数据沉淀。',
  'guide.modules': '工具与数据模块',
  'guide.module': '模块',
  'guide.description': '说明',
  'guide.rhythm': '日常节奏',
  'guide.configEntry': '配置入口',
  'guide.configDesc': '首次使用前在设置页配置 Supabase、LLM 模型与数据源；生产环境里，信号、持仓和个人设置会按用户隔离。',
  'guide.workflow.chat.title': '读盘室',
  'guide.workflow.chat.desc': '用自然语言串联行情查询、单股诊断、漏斗选股、持仓检查和调仓方案。',
  'guide.workflow.analysis.title': '单股分析',
  'guide.workflow.analysis.desc': '支持 A 股、ETF、美股、港股，围绕 Wyckoff 阶段、量价结构、支撑压力生成诊断。',
  'guide.workflow.portfolio.title': '持仓诊断',
  'guide.workflow.portfolio.desc': '白名单用户直接诊断数据库持仓，普通用户手动录入持仓后读取行情并生成风险建议。',
  'guide.tool.market': '市场水温',
  'guide.tool.market.detail': '读取大盘、A50、VIX 与风险状态，作为所有判断的先验条件。',
  'guide.tool.tracking': '形态复盘',
  'guide.tool.tracking.detail': '沉淀形态入选后的价格、状态、来源和后续复盘结果。',
  'guide.tool.signal': '信号池',
  'guide.tool.signal.detail': '汇总待确认、已确认、过期、拒绝等信号，保留完整处理链路。',
  'guide.tool.tail': '尾盘记录',
  'guide.tool.tail.detail': '记录尾盘买入候选、规则分、优先级和 LLM 决策。',
  'guide.tool.export': '数据导出',
  'guide.tool.export.detail': '把复盘、信号、持仓、尾盘记录导出为后续复盘材料。',
  'guide.tool.model': '模型设置',
  'guide.tool.model.detail': '管理默认模型、备用模型、数据源 Key 和前端调用配置。',
  'guide.playbook.pre': '盘前',
  'guide.playbook.pre.text': '先看市场水温，再筛候选池，避免在系统性风险较高时孤立看个股。',
  'guide.playbook.mid': '盘中',
  'guide.playbook.mid.text': '围绕重点股票做单股分析，用持仓和形态复盘校准风险暴露。',
  'guide.playbook.tail': '尾盘',
  'guide.playbook.tail.text': '复查尾盘候选和信号池，把需要执行或观察的标的沉淀到记录里。',
  'guide.playbook.review': '复盘',
  'guide.playbook.review.text': '导出关键数据，结合读盘室对话形成下一次交易前的上下文。',
  'market.riskOn': '偏强',
  'market.neutral': '中性',
  'market.riskOff': '偏弱',
  'market.crash': '极弱',
  'market.blackSwan': '恶劣',
  'market.optimistic': '乐观',
  'market.cautiouslyOptimistic': '谨慎乐观',
  'market.cautious': '谨慎',
  'market.defensive': '保守',
  'market.mainIndex': '上证',
} as const

const EN: Record<keyof typeof ZH, string> = {
  'app.subtitle': 'Intelligent research assistant',
  'nav.chat': 'Reading Room',
  'nav.analysis': 'Stock Analysis',
  'nav.battle': 'Stock Battle',
  'nav.portfolio': 'Position Diagnosis',
  'nav.tracking': 'Tracking',
  'nav.tailBuy': 'Tail Buy Logs',
  'nav.export': 'Data Export',
  'nav.guide': 'Guide',
  'nav.capabilities': 'Capability Map',
  'nav.settings': 'Settings',
  'external.home': 'Homepage',
  'external.github': 'GitHub',
  'action.logout': 'Log out',
  'action.refresh': 'Refresh',
  'action.save': 'Save',
  'action.cancel': 'Cancel',
  'action.delete': 'Delete',
  'prefs.theme': 'Theme',
  'prefs.language': 'Language',
  'prefs.light': 'Light',
  'prefs.dark': 'Dark',
  'prefs.switchToEnglish': 'Switch to English',
  'prefs.switchToChinese': '切换到中文',
  'common.loading': 'Loading...',
  'common.empty': 'No data',
  'common.code': 'Code',
  'common.name': 'Name',
  'common.date': 'Date',
  'common.stockCode': 'Stock / ETF code',
  'common.exampleCode': 'A-share/ETF: 601318 · US: AAPL · HK: 00700',
  'common.configureFirst': 'Please configure in Settings first',
  'common.invalidStockCode': 'Enter a valid code (A-share/ETF: 6 digits, US: ticker, HK: 5 digits)',
  'common.marketHint': 'Supports A-share, ETF, US & HK stocks · US/HK requires',
  'common.tickflowLink': 'TickFlow data source',
  'common.rows': 'rows',
  'common.stocks': 'stocks',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.register': 'Sign up',
  'login.processing': 'Processing...',
  'login.hasAccount': 'Already have an account?',
  'login.noAccount': 'No account yet?',
  'login.operationFailed': 'Operation failed',
  'login.rememberAccount': 'Remember account',
  'login.passwordManagerHint': 'Password saving stays with your browser or system password manager',
  'settings.title': 'Settings',
  'settings.account': 'Account',
  'settings.saved': 'Saved',
  'settings.saveFailed': 'Save failed: {message}',
  'settings.saving': 'Saving...',
  'settings.saveConfig': 'Save settings',
  'settings.dataSources': 'Data sources',
  'settings.tickflowPromo': 'TickFlow market data source (supports this project)',
  'settings.purchaseLink': 'Purchase link',
  'settings.modelConfig': 'Model configuration',
  'settings.oneRoutePromo': '1Route model gateway (supports this project)',
  'settings.provider': 'Reading Room provider',
  'settings.oneRouteNoAccount': 'No 1Route account yet?',
  'settings.oneRouteInvite': 'Open via purchase link',
  'settings.apiKey': 'API Key',
  'settings.model': 'Model',
  'settings.baseUrl': 'Base URL',
  'settings.notifications': 'Notifications',
  'settings.feishuWebhook': 'Feishu Webhook',
  'settings.wecomWebhook': 'WeCom Webhook',
  'settings.dingtalkWebhook': 'DingTalk Webhook',
  'analysis.title': 'Stock Analysis',
  'analysis.missingTitle': 'One more setup step before analysis',
  'analysis.missingModel': 'Configure the Reading Room model API Key and model name',
  'analysis.missingDataSource': 'Configure the TickFlow stock data API Key',
  'analysis.goSettings': 'Go to Settings',
  'analysis.modelRequirement': 'Reading Room model API Key / model',
  'analysis.dataRequirement': 'TickFlow stock data API Key',
  'analysis.missingPrefix': 'Please complete setup in Settings: {items}',
  'analysis.configError': 'Configuration looks inconsistent. Please check Settings and try again.',
  'analysis.exampleCode': 'A-share/ETF: 601318 · US: AAPL.US · HK: 00700.HK',
  'analysis.searchPlaceholder': 'Search by name or code, e.g. Ping An / AAPL / Tencent',
  'analysis.searching': 'Searching...',
  'analysis.noSearchResults': 'No matching symbol',
  'analysis.invalidStockCode': 'Enter a valid code: A-share/ETF 6 digits; US/HK TickFlow symbols such as AAPL.US / 00700.HK',
  'analysis.marketHint': 'A-share/ETF accepts 6 digits; US/HK must use TickFlow symbols (AAPL.US / 00700.HK) and requires ',
  'analysis.noKlineData': 'No valid daily K-line data was returned. Check the stock code, TickFlow Key, or try again later.',
  'analysis.failed': 'Analysis failed',
  'analysis.analyzing': 'Analyzing...',
  'analysis.progressResolve': 'Resolving code...',
  'analysis.progressKline': 'Fetching K-line...',
  'analysis.progressLLM': 'Model analyzing...',
  'analysis.start': 'Start analysis',
  'analysis.reportTitle': 'Wyckoff Research Report',
  'analysis.chartTitle': 'Last 320 Trading Days Structure',
  'analysis.chartSubtitle': 'Candles, moving averages, support/resistance, and Wyckoff markers are derived from TickFlow daily data',
  'analysis.emptyTitle': 'Enter a stock code to start Wyckoff analysis',
  'analysis.emptySubtitle': 'Configure TickFlow Key to display K-line charts',
  'chat.title': 'Reading Room',
  'chat.noApiKey': 'API Key not configured',
  'chat.newChat': 'New chat',
  'chat.emptyTitle': 'I read only supply, demand, and operator behavior',
  'chat.tryAsk': 'Try asking:',
  'chat.fullVersionPrefix': 'The web app does not yet support chat history, Agent memory, or background jobs',
  'chat.unlockFull': 'Unlock the full version',
  'chat.generating': 'Generating...',
  'chat.thinking': 'Thinking...',
  'chat.placeholder': 'Type a message...',
  'chat.configureLLM': 'Please configure an LLM API Key in Settings first',
  'chat.requestFailed': 'Request failed',
  'chat.toolCalls': '{count} tool calls',
  'chat.reasoningSteps': '{count} reasoning steps',
  'chat.prompt.portfolio': 'What positions do I hold?',
  'chat.prompt.market': 'How is the market?',
  'chat.prompt.recent': 'Recent pattern review records?',
  'chat.prompt.search': 'Search CATL for me',
  'chat.prompt.screen': 'Screen stocks for me',
  'chat.prompt.strategy': 'Give me an action plan',
  'tool.search_stock': 'Search stocks',
  'tool.view_portfolio': 'View portfolio',
  'tool.market_overview': 'Market temperature',
  'tool.market_history': 'Market history',
  'tool.query_recommendations': 'Wyckoff Pattern Review',
  'tool.query_tail_buy': 'Tail buy records',
  'tool.plan_portfolio_update': 'Portfolio plan',
  'tool.execute_portfolio_update': 'Execute portfolio update',
  'tool.analyze_stock': 'Stock diagnosis',
  'tool.screen_stocks': 'Funnel screener',
  'tool.generate_ai_report': 'AI report',
  'tool.generate_strategy_decision': 'Strategy advice',
  'portfolio.title': 'Position Diagnosis',
  'portfolio.whitelistSubtitle': 'Whitelist users can diagnose database positions directly with live market data.',
  'portfolio.manualSubtitle': 'Enter a current position to trigger market-data and model diagnosis. Upgrade guidance appears when data-source quota or concurrency is limited.',
  'portfolio.dbMode': 'Database positions',
  'portfolio.manualMode': 'Manual entry',
  'portfolio.missingModel': 'Configure the Reading Room model API Key and model name first',
  'portfolio.failed': 'Position diagnosis failed',
  'portfolio.invalidCode': 'Enter a valid code: A-share/ETF 6 digits; US/HK TickFlow symbols such as AAPL.US / 00700.HK',
  'portfolio.totalAssets': 'Total assets (cost)',
  'portfolio.freeCash': 'Available cash',
  'portfolio.positionCount': 'Positions',
  'portfolio.positionCost': 'Position cost',
  'portfolio.empty': 'No positions yet. Add them via CLI or the Reading Room Agent.',
  'portfolio.emptyDb': 'No database positions yet. Add positions via the Reading Room or CLI, then come back for diagnosis.',
  'portfolio.code': 'Stock code',
  'portfolio.name': 'Stock name',
  'portfolio.shares': 'Shares',
  'portfolio.costPrice': 'Cost price',
  'portfolio.buyDate': 'Entry date',
  'portfolio.action': 'Action',
  'portfolio.analyzeThis': 'Diagnose',
  'portfolio.startDiagnosis': 'Start diagnosis',
  'portfolio.dataHint': 'Diagnosis reads the latest 320 daily bars. TickFlow upgrade guidance appears when data-source access, quota, or concurrency is limited.',
  'portfolio.snapshot': 'Position snapshot',
  'portfolio.fullDiagnosis': 'Full diagnosis',
  'portfolio.fullDiagnosisHint': 'Analyze all positions + cash allocation',
  'portfolio.fullLoading': 'Analyzing all positions...',
  'portfolio.addPosition': 'Add position',
  'battle.title': 'Stock Battle',
  'battle.subtitle': 'Enter any number of symbols. The app fetches TickFlow daily bars concurrently, compares relative strength, and returns a Wyckoff-style battle result.',
  'battle.inputLabel': 'Stock codes or names',
  'battle.inputHint': 'Separate entries by newline, space, or comma. Examples: Ping An, AAPL, 00700.HK. No input count limit.',
  'battle.start': 'Start battle',
  'battle.running': 'Battling...',
  'battle.missingModel': 'Configure the Reading Room model API Key and model name first',
  'battle.overlay': 'Overlay',
  'battle.separate': 'Separate charts',
  'battle.overlayLimit': 'Overlay count',
  'battle.selectAll': 'Select all',
  'battle.clearAll': 'Clear',
  'battle.score': 'Strength',
  'battle.drawdown': 'Drawdown',
  'battle.report': 'Battle result',
  'tracking.title': 'Wyckoff Pattern Review',
  'tracking.description': 'This page shows data for the latest 30 review trading dates. Dates are based on records in the database, not continuous calendar days.',
  'tracking.range': 'Current retained range: {oldest} to {latest}.',
  'tracking.window': 'Review date window',
  'tracking.windowOption': 'Last {size} review dates',
  'tracking.currentWindow': 'Current window: {oldest} to {latest}, {count} review dates, {rows} records',
  'tracking.coveredStocks': 'Covered stocks',
  'tracking.avgChange': 'Avg change over last {size} review dates',
  'tracking.bestChange': 'Best change',
  'tracking.worstChange': 'Worst change',
  'tracking.totalRecommendations': 'Total selections',
  'tracking.winRate': 'Win rate',
  'tracking.avgWin': 'Avg win',
  'tracking.avgLoss': 'Avg loss',
  'tracking.profitFactor': 'Profit factor',
  'tracking.times': 'times',
  'tracking.searchPlaceholder': 'Search code or name...',
  'tracking.onlyAI': 'AI selections only',
  'tracking.sortDate': 'Sort by date',
  'tracking.sortChange': 'Sort by change',
  'tracking.sortMfe': 'Sort by MFE',
  'tracking.sortMae': 'Sort by MAE',
  'tracking.sortScore': 'Sort by signal score',
  'tracking.sortRecommendCount': 'Sort by selections',
  'tracking.sortDesc': 'Descending',
  'tracking.sortAsc': 'Ascending',
  'tracking.recommendDate': 'Selection date',
  'tracking.recommendCount': 'Selections',
  'tracking.initialPrice': 'Initial price',
  'tracking.currentPrice': 'Current price',
  'tracking.changePct': 'Change',
  'tracking.score': 'Signal score',
  'tracking.scoreRaw': 'Pattern',
  'tracking.scorePriority': 'Priority',
  'tracking.mfePct': 'MFE',
  'tracking.maePct': 'MAE',
  'tracking.rangeAmpPct': 'Range',
  'tracking.empty': 'No review records',
  'tracking.tabCN': 'A-Share',
  'tracking.tabUS': 'US',
  'tracking.tabHK': 'HK',
  'tracking.betaLocked': 'This feature is in beta. Contact the developer for access.',
  'tailBuy.title': 'Tail Buy Logs',
  'tailBuy.total': '{count} records',
  'tailBuy.empty': 'No tail-buy records yet',
  'tailBuy.emptySubtitle': 'Refresh after the next tail-buy strategy run',
  'tailBuy.signal': 'Signal',
  'tailBuy.ruleScore': 'Rule score',
  'tailBuy.priorityScore': 'Priority score',
  'tailBuy.llmDecision': 'LLM decision',
  'tailBuy.reason': 'Reason',
  'export.title': 'Data Export',
  'export.days': 'Lookback days',
  'export.adjust': 'Adjustment',
  'export.qfq': 'Forward adjusted',
  'export.hfq': 'Backward adjusted',
  'export.noneAdjust': 'Unadjusted',
  'export.fetching': 'Fetching...',
  'export.fetch': 'Fetch data',
  'export.configureTickflow': 'Please configure TickFlow API Key in Settings first',
  'export.apiError': 'TickFlow API error ({status}): {message}',
  'export.noData': 'No valid data returned. Check the stock code or try again later.',
  'export.failed': 'Export failed',
  'export.streamlitLink': 'Use the Streamlit version for full export ->',
  'export.downloadCsv': 'Download CSV ({fileName})',
  'export.previewCount': '{count} rows (previewing first 10)',
  'export.previewCountMore': '10+ rows (previewing first 10)',
  'export.emptyTitle': 'Enter a stock code to export historical OHLCV CSV',
  'export.emptySubtitle': 'Powered by TickFlow API, with forward/backward adjustment support',
  'export.needBatch': 'Need batch export or custom data sources? Open Streamlit ->',
  'guide.title': 'Guide',
  'guide.subtitle': 'Wyckoff intelligent research assistant organizes reading, screening, tracking, portfolio, and review workflows.',
  'guide.core': 'Core features',
  'guide.coreDesc': 'From natural-language market reading to structured data capture.',
  'guide.modules': 'Tools and data modules',
  'guide.module': 'Module',
  'guide.description': 'Description',
  'guide.rhythm': 'Daily rhythm',
  'guide.configEntry': 'Configuration',
  'guide.configDesc': 'Before first use, configure Supabase, LLM models, and data sources in Settings. Signals, portfolios, and personal settings are isolated by user in production.',
  'guide.workflow.chat.title': 'Reading Room',
  'guide.workflow.chat.desc': 'Connect market queries, stock diagnosis, funnel screening, portfolio checks, and rebalancing plans in natural language.',
  'guide.workflow.analysis.title': 'Stock Analysis',
  'guide.workflow.analysis.desc': 'Supports A-share, ETF, US & HK stocks. Generates diagnosis around Wyckoff phase, price-volume structure, support/resistance, and risk notes.',
  'guide.workflow.portfolio.title': 'Position Diagnosis',
  'guide.workflow.portfolio.desc': 'Whitelist users diagnose database positions directly; other users enter holdings manually before market-data diagnosis.',
  'guide.tool.market': 'Market temperature',
  'guide.tool.market.detail': 'Reads broad market, A50, VIX, and risk regime as priors for every decision.',
  'guide.tool.tracking': 'Pattern review',
  'guide.tool.tracking.detail': 'Captures prices, status, source, and follow-up results after pattern selections.',
  'guide.tool.signal': 'Signal pool',
  'guide.tool.signal.detail': 'Collects pending, confirmed, expired, and rejected signals while preserving the full processing chain.',
  'guide.tool.tail': 'Tail buy logs',
  'guide.tool.tail.detail': 'Records tail-buy candidates, rule scores, priority scores, and LLM decisions.',
  'guide.tool.export': 'Data export',
  'guide.tool.export.detail': 'Exports review records, signals, holdings, and tail-buy records for later analysis.',
  'guide.tool.model': 'Model settings',
  'guide.tool.model.detail': 'Manages default models, fallback models, data-source keys, and frontend call configuration.',
  'guide.playbook.pre': 'Pre-market',
  'guide.playbook.pre.text': 'Check market temperature first, then screen candidates to avoid reading stocks in isolation when systemic risk is high.',
  'guide.playbook.mid': 'Intraday',
  'guide.playbook.mid.text': 'Analyze key stocks while using portfolio and pattern review to calibrate risk exposure.',
  'guide.playbook.tail': 'Tail session',
  'guide.playbook.tail.text': 'Review tail-buy candidates and signal pools, then preserve symbols that need action or observation.',
  'guide.playbook.review': 'Review',
  'guide.playbook.review.text': 'Export key data and use Reading Room conversations to prepare context for the next trading session.',
  'market.riskOn': 'Risk-on',
  'market.neutral': 'Neutral',
  'market.riskOff': 'Risk-off',
  'market.crash': 'Very weak',
  'market.blackSwan': 'Severe',
  'market.optimistic': 'Optimistic',
  'market.cautiouslyOptimistic': 'Cautiously optimistic',
  'market.cautious': 'Cautious',
  'market.defensive': 'Defensive',
  'market.mainIndex': 'SSE',
}

export type TranslationKey = keyof typeof ZH

type TranslateVars = Record<string, string | number | null | undefined>

interface PreferencesContextValue {
  locale: Locale
  theme: ThemeMode
  setLocale: (locale: Locale) => void
  setTheme: (theme: ThemeMode) => void
  toggleTheme: () => void
  t: (key: TranslationKey, vars?: TranslateVars) => string
}

const PreferencesContext = createContext<PreferencesContextValue | null>(null)

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => readLocale())
  const [theme, setThemeState] = useState<ThemeMode>(() => readTheme())

  useEffect(() => {
    document.documentElement.lang = locale
    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale)
  }, [locale])

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
    document.documentElement.style.colorScheme = theme
    window.localStorage.setItem(THEME_STORAGE_KEY, theme)
  }, [theme])

  const setLocale = useCallback((nextLocale: Locale) => setLocaleState(nextLocale), [])
  const setTheme = useCallback((nextTheme: ThemeMode) => setThemeState(nextTheme), [])
  const toggleTheme = useCallback(() => setThemeState((c) => c === 'dark' ? 'light' : 'dark'), [])
  const t = useCallback((key: TranslationKey, vars?: TranslateVars): string => translate(locale, key, vars), [locale])

  const value = useMemo(() => ({ locale, theme, setLocale, setTheme, toggleTheme, t }), [locale, theme, setLocale, setTheme, toggleTheme, t])

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  )
}

export function usePreferences(): PreferencesContextValue {
  const context = useContext(PreferencesContext)
  if (!context) {
    throw new Error('usePreferences must be used inside PreferencesProvider')
  }
  return context
}

function translate(locale: Locale, key: TranslationKey, vars?: TranslateVars): string {
  const template = (locale === 'en-US' ? EN : ZH)[key] || ZH[key]
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (match, name) => {
    const value = vars[name]
    return value == null ? match : String(value)
  })
}

function readLocale(): Locale {
  const saved = window.localStorage.getItem(LOCALE_STORAGE_KEY)
  return saved === 'en-US' || saved === 'zh-CN' ? saved : 'zh-CN'
}

function readTheme(): ThemeMode {
  const saved = window.localStorage.getItem(THEME_STORAGE_KEY)
  if (saved === 'light' || saved === 'dark') return saved
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}
